import Head from 'next/head'
import { Inter } from '@next/font/google'
import  Navbar  from './components/Navbar'
import  Hero  from './components/Hero'
import Reason from './components/Reason'
import Box from './components/Box'
import Menu from './components/Menu'
import Footer from './components/Footer'
import World from './components/World'
import Construct from './components/Construct'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://stijndv.com" />
      <link rel="stylesheet" href="https://stijndv.com/fonts/Eudoxus-Sans.css" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='bg-gray-700'>
         <Navbar/>
         <Hero/>
         <Reason/>
         <Box/>
         <Menu/>
         <World/>
         <Footer/>
          
        </div>
      </main>
    </>
  )
}
