import Head from 'next/head'
import { useForm } from 'react-hook-form'
import { motion } from 'framer-motion'
import { TitleText, TypingText } from './components/CustomText'
import { useEffect, useState } from 'react';

const staggerContainer = (staggerChildren: number, delayChildren: number) => ({
  hidden: {},
  show: {
    transition: {
      staggerChildren,
      delayChildren,
    },
  },
});

export const zoomIn = (delay:number, duration:number) => ({
  hidden: {
    scale: 0,
    opacity: 0,
  },
  show: {
    scale: 1,
    opacity: 1,
    transition: {
      type: 'tween',
      delay,
      duration,
      ease: 'easeOut',
    },
  },
});

type FormValues = {
  firstname: string
  lastname : string
  streetaddress : string
  city : string
  zip : string
  phone : string
  country : string
}

export default function Home() {

  const {
    register,
    handleSubmit,
    watch,
    reset,
    getValues,
    formState,
    formState: { errors, isSubmitting, defaultValues },
  } = useForm<FormValues>({
    defaultValues: {
      firstname: "",
      lastname : "",
      streetaddress : "",
      city : "",
      zip : "",
      phone : "",
    }
  });

  useEffect(()=>{
    if(formState.isSubmitSuccessful){
        reset({
          firstname: "",
          lastname : "",
          streetaddress : "",
          city : "",
          zip : "",
          phone : "",
          country : "Available Country",

        })
        alert("Successful Login")
    }
}, [formState, reset])

  console.log(watch(['firstname','lastname','streetaddress','city','zip','phone']));


  return (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="preconnect" href="https://stijndv.com" />
      <link rel="stylesheet" href="https://stijndv.com/fonts/Eudoxus-Sans.css" />
      <link rel="icon" href="/favicon.ico" />
    </Head>


    <main className='bg-gray-700'>
    <section className='sm:p-16 xs:p-8 px-6 py-12 w-screen h-screen flex justify-center items-center '>
      <div className='mx-auto max-w-[1280px] w-full h-full flex justify-center items-center '>
        <form action="" className='flex flex-col gap-4 items-center'
          onSubmit={handleSubmit((data)=>{
          console.log(data)
          })}>

          <motion.div className='flex flex-col' variants={staggerContainer(1, 1)} initial="hidden" whileInView="show" viewport={{ once: false, amount: 0.25 }}>
            <TypingText title='| Get started' styling='text-center' />
            <TitleText title='Shipping Information' styling='text-center font-extrabold ' />
          </motion.div>
          
          <motion.div variants={zoomIn(0.4,1)} initial="hidden" whileInView="show" 
          className=' flex-col grid sm:grid-cols-2 gap-5'>

            <div className='flex flex-col'>
              <input type="text" placeholder='First Name' className='p-2 rounded-xl h-9' 
             {...register("firstname", { 
              required: 'please fill out the box', 
              })}/>
             <p className='text-red-300'> {errors.firstname?.message} </p>
            </div >
            
            <div className='flex flex-col'>
              <input type="text" placeholder='Last Name' className='p-2 rounded-xl h-9'  
              {...register("lastname", { 
                required: 'please fill out the box', 
                })}/>
              <p className='text-red-300'> {errors.lastname?.message} </p>
            </div>

            <div className='flex flex-col'>
              <input type="text" placeholder='Street Address' className='p-2 rounded-xl h-9' 
             {...register("streetaddress", { 
              required: 'please fill out the box', 
              })}/>
             <p className='text-red-300'> {errors.streetaddress?.message} </p>
            </div >
            
            <div className='flex flex-col'>
              <input type="text" placeholder='City' className='p-2 rounded-xl h-9'  
             {...register("city", { 
              required: 'please fill out the box', 
              })}/>
              <p className='text-red-300'> {errors.city?.message} </p>
            </div>

            <div className='flex flex-col'>
              <input type="text" placeholder='Zip Code' className='p-2 rounded-xl h-9' 
             {...register("zip", { 
              required: 'please fill out the box', 
              })}/>
             <p className='text-red-300'> {errors.zip?.message} </p>
            </div >
            
            <div className='flex flex-col'>
              <input type="text" placeholder='Phone Number' className='p-2 rounded-xl h-9'  
              {...register("phone", { 
                required: 'please fill out the box',
                minLength:{value:10, message:"invalid phone number"}, 
                maxLength:{value:12, message:"invalid phone number"}, 
                })}/>
              <p className='text-red-300'> {errors.phone?.message} </p>
            </div>

            <div className='flex flex-col col-span-2'>   
              <select placeholder='Gender' {...register("country", { required:"please select a country" })} className='p-2 rounded-xl h-9'>
                <option value="" disabled selected className='opacity-50'>Available Country</option> 
                <option value="Male">Indonesia</option>
                <option value="Female">Singapore</option>
                <option value="Other">Malaysia</option>
              </select>
              <p className='text-red-300'> {errors.country?.message} </p>
            </div> 
          </motion.div>

          <motion.input variants={zoomIn(0.4,1)} initial="hidden" whileInView="show" whileHover={{ scale: 1.1 }} transition={{ type: "spring", stiffness: 100, damping: 8 }}
            type="submit" className='rounded-full p-1 bg-slate-900 text-white hover:text-slate-900 
                hover:bg-slate-300 cursor-pointer mt-3 max-w-[300px] w-[300px]'/>
        </form>
      </div>
    </section>
    </main>
  </>
  )
}

