import Head from 'next/head'
import { useEffect, useState } from 'react';
import { fetchData } from '@/pages/api/basicApi';

type dataType = {
    id: number,
    title: string,
}

export default function Home() {

    const [data, setData] = useState<dataType[]>([]);

    useEffect(() => {
        const getData = async () => {
          const result = await fetchData();
          setData(result);
        };
    
        getData();
      }, []);

  return (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="preconnect" href="https://stijndv.com" />
      <link rel="stylesheet" href="https://stijndv.com/fonts/Eudoxus-Sans.css" />
      <link rel="icon" href="/favicon.ico" />
    </Head>


    <main className='bg-gray-700'>
    <section className='sm:p-16 xs:p-8 px-6 py-12 w-screen h-screen flex justify-center items-center '>
      <div className='mx-auto max-w-[1280px] w-full h-full'>
        
        <div className='flex flex-col items-center py-10 mx-auto'>
            <h1 className='text-white font-bold text-4xl'>My Next.js App</h1>
            <ul className='flex flex-wrap'>
                {data.map((item) => (
                    
                       <li key={item.id}>
                        <div className='text-slate-700 p-2 bg-slate-300 rounded-xl m-2 w-[90px]'>
                        <div >
                            {item.id}
                        </div>
                        <div className='line-clamp-3'>
                            {item.title}
                        </div>
                          </div> 
                        </li> 
                 
                ))}
                </ul>
        </div>

      </div>
    </section>
    </main>
  </>
  )
}

