import Head from 'next/head'
import { useEffect, useState } from 'react';
import { getPopularMovies } from '@/pages/api/tmdbApi';
import Image from 'next/image';
import { Carter_One } from '@next/font/google';

type dataType = {
    id: number,
    title: string,
    poster_path: string,
    release_date: string,

}

export default function Home() {

    const [movies, setMovies] = useState<dataType[]>([]);
    const [isLoading, setIsLoading] = useState<boolean>(false);
    const [error, setError] = useState<string>('');

    useEffect(() => {
      const fetchMovies = async () => {
        setIsLoading(true);

        try{
            const data = await getPopularMovies();
        setMovies(data.results);
        } catch (error:any) {
          setError(error.message);
        }
        setIsLoading(false);
      
      };
      fetchMovies();
    }, []);

    if (isLoading) {
      return <p>Loading...</p>;
    }
  
    if (error) {
      return <p>{error}</p>;
    }
  

  return (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="preconnect" href="https://stijndv.com" />
      <link rel="stylesheet" href="https://stijndv.com/fonts/Eudoxus-Sans.css" />
      <link rel="icon" href="/favicon.ico" />
    </Head>


    <main className='bg-gray-700'>
    <section className='sm:p-16 xs:p-8 px-6 py-12 w-screen h-screen flex justify-center items-center '>
      <div className='mx-auto max-w-[1280px] w-full h-full'>
        
        <div className='flex flex-col items-center py-10 mx-auto'>
            <h1 className='text-white font-bold text-4xl'>My Next.js App</h1>
            <ul className='flex flex-wrap'>
                {movies.map((movie) => (
                    
                    <div className='p-2 bg-slate-200 m-2 w-[90px]'>
                       <div>
                        <Image src={`https://image.tmdb.org/t/p/w500${movie.poster_path}`}
                        alt="movie"
                        width={200}
                        height={300}/>
                    </div>
                    <div >
                          <li key={movie.id}>
                         <div className='text-slate-700 p-2 bg-slate-300 rounded-xl m-2 w-full'>
                         <div >
                             {movie.id}
                         </div>
                         <div className='line-clamp-3'>
                             {movie.title}
                         </div>
                           </div> 
                         </li> 
                    </div>
                    </div>
                   

                    
                 
                ))}
                </ul>
        </div>

      </div>
    </section>
    </main>
  </>
  )
}

