import Head from 'next/head'
import { useQuery } from 'react-query';
import type { NextPage } from 'next';
import Image from 'next/image';

interface Post {
    id: number;
    title: string;
    body: string;
    poster_path: string;
  }

  interface QueryError {
    message: string,
  }

  const QUERY_KEY = 'https://jsonplaceholder.typicode.com/posts';

export default function Home() {

    const { isLoading, error, data } = useQuery<Post[]>(QUERY_KEY, async () => {
        const response = await fetch(QUERY_KEY);
        return response.json();
      });

      if (isLoading) return <div>Loading...</div>;
      if (error){
        const queryError = error as QueryError
         return <div>Error: {queryError.message}</div>;
      }
  

  return (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="preconnect" href="https://stijndv.com" />
      <link rel="stylesheet" href="https://stijndv.com/fonts/Eudoxus-Sans.css" />
      <link rel="icon" href="/favicon.ico" />
    </Head>


    <main className='bg-gray-700'>
    <section className='sm:p-16 xs:p-8 px-6 py-12 w-screen h-screen flex justify-center items-center '>
      <div className='mx-auto max-w-[1280px] w-full h-full'>

      <div className='flex flex-col items-center py-10 mx-auto'>
            <h1 className='text-white font-bold text-4xl'>My Next.js App</h1>
            <ul className='flex flex-wrap'>
                {data?.map((item) => (
                    
                    <div className='p-2 bg-slate-200 m-2 w-[90px]'>
                    <div>
                     <Image src={`https://image.tmdb.org/t/p/w500${item.poster_path}`}
                     alt="movie"
                     width={200}
                     height={300}/>
                 </div>
                 <div >
                       <li key={item.id}>
                      <div className='text-slate-700 p-2 bg-slate-300 rounded-xl m-2 w-full'>
                      <div >
                          {item.id}
                      </div>
                      <div className='line-clamp-3'>
                          {item.title}
                      </div>
                        </div> 
                      </li> 
                 </div>
                 </div>
                 
                ))}
                </ul>
        </div>
        
      </div>
    </section>
    </main>
  </>
  )
}

